---
name: deploy to environment

on:
  workflow_call:
#    inputs:
#      ENVIRONMENT:
#        description: Which environment to do deployment
#        required: true
#        type: string

#concurrency:
#  group: ${{ inputs.ENVIRONMENT }}
#  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo '${{ toJSON(github) }}'
